
production:
  adapter: postgresql
  encoding: unicode
  database: servicii_db
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: servicii_db
  pool: 5
  